//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dz_17
{
    using System;
    using System.Collections.Generic;
    
    public partial class Authors
    {
        public int Id { get; set; }
        public string FullName { get; set; }
        public int Age { get; set; }
    
        public virtual News News { get; set; }
    }
}
